language: r

cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: bioc-devel
    - os: osx
      latex: false
      r: bioc-devel
    - os: linux
      dist: trusty
      r: bioc-release
    - os: osx
      latex: false
      r: bioc-release

r_packages:
  - covr
  - testthat
  - lintr
  - lme4
  - tidyverse
  - assertthat
  - data.table
  - diffusr
  - dtplyr
  - locfdr
  - metap

bioc_packages:
  - limma
  - BiocCheck
  - BiocStyle

env:
  global:
    - r_build_args="--no-build-vignettes --no-manual"
    - r_check_args="--no-build-vignettes --no-manual --as-cran --no-examples"
    - LINTR_COMMENT_BOT=false

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
